### ISSUE TITLE
Add support for System Real-Time messages

### ISSUE THREAD

**Issue by RootAlgorithm** [micdah/RtMidi.Core#22]
From what I've seen in the code, there is no support for System Real-Time messages (0b1111_1000 - 0b1111_1111)
The messages are defined at the bottom of this list: https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message

**Comment by micdah** [comment]
@RootAlgorithm that is correct, but should not be a big issue to implement as they are quite simple messages.

I will have a look at it and notify you when a new version is available with the new message types

**Comment by igbro** [comment]
Hi Michael, I'd love to have access to Midi Clock/Start/Continue/Stop messages too.
Thanks.

**Comment by micdah** [comment]
I forgot to update here, that I have release 1.0.51 with the requested message types: https://github.com/micdah/RtMidi.Core/blob/v1.0.51/CHANGELOG.md

**Comment by maris-seimanovs-afry** [comment]
I'm not sure if this has been actually solved? I see System Common Messages but no Real-Time messages.

One problem with those messages is that they are 1 byte long and they are allowed to jump in the middle of any other message. This would require not only parsing them, but also detecting them while parsing all the other messages, otherwise Real-Time messages can break the logic of the parser.

One example is Active Sensing - some devices are sending this often. I'm wondering what would RtMidi do if such a Real-Time byte suddenly appeared in the middle of a NoteOn / Off message?

**Comment by progmars** [comment]
I'm not sure if this has been actually solved? I see System Common Messages but no Real-Time messages.

One problem with those messages is that they are 1 byte long and they are allowed to jump in the middle of any other message. This would require not only parsing them, but also detecting them while parsing all the other messages, otherwise Real-Time messages can break the logic of the parser.

One example is Active Sensing - some devices are sending this often. I'm wondering what would RtMidi do if such a Real-Time byte suddenly appeared in the middle of a NoteOn / Off message?

**Comment by micdah** [comment]
@progmars Good question, I'm more than happy to take a look at a PR if you find message types missing which should be handled or that can interfere.

Current code emits a error log on unexpected btyes, but otherwise it should not interfere with existing functionality.

There is a test suite, so I'd start by creating representative tests for the interleavings of MIDI messages and then verify the expected output, and then go about updating the decoding code to handle the new message types.
